In [1]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [4]:
addition_result = np.add(A, B)
print("Addition Result:")
print(addition_result)
print()

Addition Result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]



In [5]:
subtraction_result = np.subtract(A, B)
print("Subtraction Result:")
print(subtraction_result)
print()

Subtraction Result:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]



In [6]:
multiplication_result = np.matmul(A, B)
print("Multiplication Result:")
print(multiplication_result)
print()

Multiplication Result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]



In [7]:
A_inverse = np.linalg.inv(A)
print("Inverse of A:")
print(A_inverse)
print()

Inverse of A:
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]



In [8]:
A_transpose = np.transpose(A)
print("Transpose of A:")
print(A_transpose)
print()

Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]



In [9]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
correlation_matrix = np.corrcoef(data, rowvar=False)

print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
