Matrix Opearations using numpy

In [ ]:
import numpy as np



In [ ]:
# Create sample matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])



In [ ]:
# Addition
addition_result = np.add(A, B)
print("Addition Result:")
print(addition_result)
print()




Addition Result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]



In [ ]:
# Subtraction
subtraction_result = np.subtract(A, B)
print("Subtraction Result:")
print(subtraction_result)
print()


Subtraction Result:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]



In [ ]:
# Multiplication
multiplication_result = np.matmul(A, B)
print("Multiplication Result:")
print(multiplication_result)
print()



Multiplication Result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]



In [ ]:
# Inverse (for square matrices only)
A_inverse = np.linalg.inv(A)
print("Inverse of A:")
print(A_inverse)
print()



In [ ]:
# Transpose
A_transpose = np.transpose(A)
print("Transpose of A:")
print(A_transpose)
print()



In [ ]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print()

print("Eigenvectors:")
print(eigenvectors)
print()


In [ ]:
# Sample data
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Compute correlation matrix
correlation_matrix = np.corrcoef(data, rowvar=False)

print("Correlation Matrix:")
print(correlation_matrix)